
spring.ai.openai.api-key=


spring.ai.openai.base-url=https://openrouter.ai/api

spring.ai.openai.chat.options.chatCompletionModel=openai/gpt-oss-20b:free

spring.ai.openai.chat.options.max-tokens=1000

server.port=8081

pinecone.api.key =

pinecone.environment =us-west1-gcp
pinecone.index =codenection
