
server.port=8081

# Gemini Configuration
gemini.model.name=gemini-2.5-flash
gemini.api.key=${GEMINI_API_KEY}
gemini.api.keyList=${GEMINI_API_KEY_LIST}

# GitHub OAuth Configuration
spring.security.oauth2.client.registration.github.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email,repo