spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=${OPENAI_BASE_URL}
spring.ai.openai.chat.options.chatCompletionModel=openai/gpt-oss-20b:free
spring.ai.openai.chat.options.max-tokens=1000

server.port=${PORT}

pinecone.api.key=${PINECONE_API_KEY}
pinecone.environment =us-west1-gcp
pinecone.index =codenection

# Gemini Configuration
gemini.model.name=gemini-2.5-flash
gemini.api.key=${GEMINI_API_KEY}
gemini.api.keyList=${GEMINI_API_KEY_LIST}
